version: "3.9"
services:
  muse:
    image: mysql:8.0.29
    container_name: muse
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "muse"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci